version: "3.8"
services:
  db:    
    environment:
      MYSQL_DATABASE: 'db'   
      MYSQL_USER: 'username'
      MYSQL_PASSWORD: 'password'      
      MYSQL_ROOT_PASSWORD: 'password'
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    environment:
      - PORT=8012